name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Deploy to Dokku'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to Dokku
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
           git subtree push --prefix api dokku master
     
