name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
      tags:
        description: 'Deploy to Dokku'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Adding Remote Repo
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
           git remote add dokku dokku@35.233.143.58:mintro-api
    
    
      - name: Push to Dokku
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
           git subtree push --prefix api dokku master
     
