name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Deploy to Dokku'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - id: deploy
      name: Deploy to dokku
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: '35.233.143.58'
          app-name: 'mintro-api'
          remote-branch: 'main'
     
